---
local_paths:
    datalad:
    # paths to the datalad datasets contained
    # in the datalad superdataset
        OpenNeuroDatasets: /home/remi/datalad/datasets.datalad.org/openneuro
        OpenNeuroDerivatives: /home/remi/datalad/datasets.datalad.org/openneuro-derivatives
    openneuro:
        OpenNeuroDatasets: /home/remi/openneuro/
